/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import java.net.SocketOption;

public class Library {
    public boolean someLibraryMethod() {

        return true;
    }

    public static void main (String[] args){

//        RESTAURANT

          // NEW RESTAURANT OBJ
        Restaurant kfc = new Restaurant("kfc", 2.0, "$");
        System.out.println(kfc);

         //  NEW REVIEW OBJ
        Review rev = new Review("Good restaurant","Meghem", 3.0);
        Review rev1 = new Review("Good restaurant","Mezel", 4.0);
        Review rev2 = new Review("Good restaurant","Metlak", 2.0);

         //  ADD REVIEWS
        kfc.addReview(rev);
        kfc.addReview(rev1);
        kfc.addReview(rev2);

         //  PRINT REVIEWS AND kfc OBJ
        System.out.println(kfc.getReviews());
         System.out.println(kfc);

//         SHOP

        //  NEW SHOP OBJs
         Shop carrefour = new Shop("carrefour","supermarket",3);
        System.out.println(carrefour);

        //  NEW REVIEWS OBJs
        Review rev3 = new Review("bad","wdha", 7);
        Review rev4 = new Review("bad","ferdos", 3);

        //  ADD REVIEWS
        carrefour.addReview(rev3);
        carrefour.addReview(rev4);

        //  PRINT REVIEWS AND carrefour OBJ
        System.out.println(carrefour.getReviews());
        System.out.println(carrefour);

//        THEATER

        //   NEW THEATER OBJ
        Theater movie = new Theater("azzam");
        System.out.println(movie);

        //   ADD MOVIES TO MOVIE LIST
        movie.addMovie("lion");
        movie.addMovie("tiger");

       //    PRINT MOVIES
        System.out.println(movie);

       //    PRINT MOVIE LIST
        System.out.println(movie.getMovies());

       //     ADD MOVIES TO REVIEW
        movie.addNewRev("good","oglah",4);

      //      NEW REVIEW OBJ
        Review rev5 = new Review("good","ahmad", 3);

        movie.addNewRev(rev5,"lion");
        movie.removeMovie("tiger");
        movie.addNewRev(rev5,"tiger");
        System.out.println(movie);
        System.out.println(movie.getReviews());
    }
}
