/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {


    @Test public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    //    RESTAURANT TEST
    @Test
    public void constructorTestRes(){
        Restaurant test = new Restaurant("kfc", 4 ,"$");
        String expectedName = "kfc";
        assertEquals(expectedName,test.getName());
        assertEquals(4,test.getNumberOfStars(),1.2);
        assertEquals("$",test.getPriceCategory());
    }


    @Test
    public void testToStringRestaurant() {
        Restaurant test = new Restaurant("kfc", 4 ,"$");
        assertEquals("Restaurant{name='kfc', numberOfStars=4.0, priceCategory=$}",String.valueOf(test));

    }

    @Test
    public void TestAddReviewRes(){
        Restaurant test = new Restaurant("kfc", 4 ,"$");
        Review test1 = new Review("Good restaurant","Meghem",5);
        test.addReview(test1);
        assertEquals("return true if add review", 1, test.getReviews().size());
    }

    //   REVIEW TEST
    @Test
    public void constructorTestRev(){
        Review test = new Review("Good restaurant", "Meghem",5);
        assertEquals("Good restaurant",test.getBody());
        assertEquals("Meghem",test.getAuthor());
        assertEquals(5,test.getStars(),0.1);

    }

    @Test
    public void testRev(){
        Review test = new Review("Good restaurant","Meghem",5);
        assertEquals("Review{body='Good restaurant', author='Meghem', stars=5.0}",String.valueOf(test));    }

    //    SHOP TEST
    @Test
    public void testToStringShop() {
        Shop test = new Shop("carrefour","supermarket",3);
        assertEquals("Shop{name='carrefour', description='supermarket', numOfDollarSigns=3}",String.valueOf(test));

    }


    @Test
    public void constructorTestShop(){
        Shop test = new Shop("carrefour", "supermarket",3);
        String expectedName = "carrefour";
        assertEquals(expectedName,test.getName());
        assertEquals("supermarket",test.getDescription());
        assertEquals(3,test.getNumOfDollarSign());

    }

//    THEATER TESTS
    @Test
    public void constructorTheater() {
    Theater movie = new Theater("azzam");
    assertEquals("azzam",movie.getName());
    }

    @Test
    public void testToStringTheater() {
        Theater test = new Theater("azzam");
        assertEquals("Theater{name='azzam', movies[], reviews={}}",String.valueOf(test));

    }

    @Test
    public void TestAddReview(){
        Theater testAdd = new Theater("test");
        testAdd.addNewRev("test","test",5);
        assertEquals("return true if add review", 1, testAdd.getReviews().size());
    }
    @Test
    public void TestAddAndRemoveReview(){
        Theater testAdd = new Theater("test");
        testAdd.addMovie("test1");
        assertEquals("return true if add movie", 1, testAdd.getMovies().size());
        testAdd.removeMovie("test1");
        assertEquals("return true if remove movie", 0, testAdd.getMovies().size());
    }


}
